"use client";
import {useEffect,useState} from "react";import {useRouter} from"next/navigation";import AppShell from"@/components/AppShell";
type Payment={id:string;amount:number;plan:string;status:string;reference:string;receiptUrl?:string;receiptFilename?:string;adminNote?:string;user?:{fullName:string;email:string}};
type Badge={id:string;name:string;description:string;icon:string;minReferrals:number}; type RefUser={id:string;fullName:string;email:string;referralCode:string;_count:{referrals:number};badges:{badge:Badge}[]};
export default function Admin(){const[payments,setPayments]=useState<Payment[]>([]);const[stats,setStats]=useState<any>(null);const[refs,setRefs]=useState<RefUser[]>([]);const[badges,setBadges]=useState<Badge[]>([]);const[msg,setMsg]=useState("");const router=useRouter();
async function load(){const[p,s,rr]=await Promise.all([fetch('/api/admin/payments'),fetch('/api/admin/stats'),fetch('/api/admin/referrals')]);if([p,s,rr].some(x=>x.status===403)){router.push('/login');return}setPayments(await p.json());setStats(await s.json());const rd=await rr.json();setRefs(rd.users||[]);setBadges(rd.badges||[])}useEffect(()=>{load()},[]);
async function review(id:string,action:string){const note=window.prompt("Optional admin note:")||"";const r=await fetch('/api/admin/payments/review',{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId:id,action,note})});const d=await r.json();setMsg(r.ok?`Payment ${action.toLowerCase()}.`:d.error||"Review failed");load()}
async function addBadge(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/referrals',{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const d=await r.json();setMsg(r.ok?"Badge created and eligible users updated.":d.error||"Could not create badge");if(r.ok)(e.currentTarget as HTMLFormElement).reset();load()}
return <AppShell title="Admin Controls" subtitle="Payments, platform health, referrals, badges and growth."><section className="stats-grid">{stats&&<><div><span className="stat-icon">◌</span><b>{stats.users}</b><span>Users</span></div><div><span className="stat-icon">▣</span><b>{stats.jobs}</b><span>Open jobs</span></div><div><span className="stat-icon">◈</span><b>{stats.pendingPayments}</b><span>Pending payments</span></div><div><span className="stat-icon">♔</span><b>{stats.premiumUsers}</b><span>Premium users</span></div><div><span className="stat-icon">✓</span><b>{stats.approvedPayments}</b><span>Approved payments</span></div><div><span className="stat-icon">₦</span><b>₦{(stats.completedCommission||0).toLocaleString()}</b><span>Completed commission</span></div></>}</section>{msg&&<p className="status app-alert">{msg}</p>}
<section className="admin-section"><div className="section-mini-heading"><div><span>REFERRAL MANAGEMENT</span><h2>Badges & ambassadors</h2></div><p>{refs.length} users tracked</p></div><div className="admin-badge-layout"><form className="app-form compact-form" onSubmit={addBadge}><label>Badge name<input name="name" required placeholder="Early Ambassador"/></label><label>Description<input name="description" required placeholder="What this badge means"/></label><label>Icon<input name="icon" defaultValue="🏅" maxLength={4}/></label><label>Minimum referrals<input name="minReferrals" type="number" min="0" required placeholder="5"/></label><button>Create badge</button></form><div className="badge-grid">{badges.map(b=><article className="badge-card" key={b.id}><span>{b.icon}</span><h3>{b.name}</h3><p>{b.description}</p><small>{b.minReferrals}+ referrals required</small></article>)}</div></div><div className="admin-list referral-admin-list">{refs.map(u=><article className="payment-row" key={u.id}><div className="payment-user"><span className="person-avatar">{u.fullName.slice(0,1).toUpperCase()}</span><div><b>{u.fullName}</b><p>{u.email}</p><small>Code: {u.referralCode}</small></div></div><div className="payment-review"><b>{u._count.referrals} referral{u._count.referrals===1?"":"s"}</b><p>{u.badges.map(x=>x.badge.icon+" "+x.badge.name).join(" · ")||"No badges"}</p></div></article>)}</div></section>
<section className="admin-section"><div className="section-mini-heading"><div><span>PAYMENT REVIEW</span><h2>Payment proofs</h2></div><p>{payments.length} submission{payments.length===1?'':'s'}</p></div><div className="admin-list">{payments.length===0?<div className="empty-state"><span>◈</span><h2>No payments yet</h2><p>Payment submissions will appear here for review.</p></div>:payments.map(x=><article key={x.id} className="payment-row"><div className="payment-user"><span className="person-avatar">{x.user?.fullName?.slice(0,1).toUpperCase()||'U'}</span><div><b>{x.user?.fullName}</b><p>{x.user?.email}</p><p>₦{x.amount.toLocaleString()} · {x.plan}</p><small>{x.reference}</small>{x.receiptUrl&&<p><a href={x.receiptUrl} target="_blank">View payment proof: {x.receiptFilename||"receipt"}</a></p>}{x.adminNote&&<p>Admin note: {x.adminNote}</p>}</div></div><div className="payment-review"><span className={`payment-status ${x.status.toLowerCase()}`}>{x.status}</span>{x.status==="PENDING"&&<div className="admin-actions"><button onClick={()=>review(x.id,"APPROVED")}>Approve</button><button className="danger-button" onClick={()=>review(x.id,"REJECTED")}>Reject</button></div>}</div></article>)}</div></section></AppShell>}