"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";

type Job = { id:string; title:string; description:string; budget:number; createdAt?:string; client?:{fullName:string} };
export default function Jobs(){
  const [jobs,setJobs]=useState<Job[]>([]),[me,setMe]=useState<any>(null),[message,setMessage]=useState(""),[selected,setSelected]=useState(""),[cover,setCover]=useState(""),[query,setQuery]=useState(""),[sort,setSort]=useState("latest");
  useEffect(()=>{fetch('/api/jobs').then(r=>r.json()).then(d=>setJobs(Array.isArray(d)?d:[]));fetch('/api/auth/me').then(r=>r.json()).then(d=>setMe(d.user));},[]);
  const filtered=useMemo(()=>jobs.filter(j=>`${j.title} ${j.description} ${j.client?.fullName||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='budget'?b.budget-a.budget:new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),[jobs,query,sort]);
  async function apply(id:string){const r=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId:id,coverLetter:cover})});const d=await r.json();setMessage(r.ok?'Application submitted successfully.':d.error||'Could not apply');if(r.ok){setSelected('');setCover('');}}
  return <AppShell title="Browse Jobs" subtitle="Discover open work opportunities and find projects that match your skills." actions={me?.role==='CLIENT'?<Link className="primary-link top-action" href="/jobs/post">＋ Post a Job</Link>:null}>
    {message&&<p className="status app-alert">{message}</p>}
    <section className="jobs-hero-v2"><div><span className="eyebrow">OPPORTUNITIES</span><h2>Find work worth doing.</h2><p>Search current opportunities and apply directly from your LeonardX workspace.</p></div><div className="jobs-hero-count"><b>{jobs.length}</b><span>open opportunities</span></div></section>
    <section className="jobs-toolbar jobs-toolbar-v2"><div className="jobs-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search jobs by title, skill or keyword..." /></div><div className="jobs-filter"><button type="button" className={sort==='latest'?'active-filter':''} onClick={()=>setSort('latest')}>Latest</button><button type="button" className={sort==='budget'?'active-filter':''} onClick={()=>setSort('budget')}>Highest budget</button></div></section>
    <div className="list-grid job-list-v2">{filtered.length===0?<div className="empty-state"><span>▣</span><h2>{jobs.length ? "No matching jobs" : "No jobs available yet"}</h2><p>{jobs.length ? "Try another keyword to find opportunities." : "New opportunities will appear here as clients publish jobs."}</p></div>:filtered.map(j=><article className="job-card job-card-v2" key={j.id}><div className="job-card-main"><div className="job-avatar">{j.title.slice(0,1).toUpperCase()}</div><div className="job-copy"><div className="job-heading"><div><span className="job-open-pill">OPEN PROJECT</span><h2>{j.title}</h2><div className="job-meta">{j.client&&<span>Posted by {j.client.fullName}</span>}</div></div><strong>₦{j.budget.toLocaleString()}</strong></div><p>{j.description}</p>{me?.role==='FREELANCER'&&(selected===j.id?<div className="apply-box"><textarea value={cover} onChange={e=>setCover(e.target.value)} placeholder="Tell the client briefly why you are a good fit"/><div><button onClick={()=>apply(j.id)}>Submit application</button><button type="button" className="ghost" onClick={()=>setSelected('')}>Cancel</button></div></div>:<button className="job-action" onClick={()=>setSelected(j.id)}>View & Apply <span>→</span></button>)}</div></div></article>)}</div>
  </AppShell>
}
