"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";
import OnlineDot from "@/components/OnlineDot";

export default function Applications() {
  const [items,setItems]=useState<any[]>([]),[me,setMe]=useState<any>(null),[msg,setMsg]=useState("");
  const load=()=>fetch("/api/applications").then(r=>r.json()).then(d=>setItems(Array.isArray(d)?d:[]));
  useEffect(()=>{load();fetch("/api/auth/me").then(r=>r.json()).then(x=>setMe(x.user))},[]);
  async function review(id:string,action:string){const r=await fetch("/api/applications/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const d=await r.json();setMsg(r.ok?"Application updated.":d.error||"Failed");load()}
  async function deliver(jobId:string,e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMsg("");const f=new FormData(e.currentTarget);const file=f.get("file");if(!(file instanceof File)||!file.size)return setMsg("Choose the finished job file.");const r=await fetch(`/api/jobs/${jobId}/delivery`,{method:"POST",body:f});const d=await r.json();setMsg(r.ok?d.message:d.error||"Delivery failed");if(r.ok)e.currentTarget.reset();load()}
  return <AppShell title={me?.role==="CLIENT"?"Applications received":"My Applications"} subtitle="Apply, get hired, deliver work and release protected escrow payments."><div className="page-inline-actions"><Link href="/escrow" className="secondary-button">Open Escrow →</Link></div>{msg&&<p className="status app-alert">{msg}</p>}<div className="list-grid">{!items.length?<div className="empty-state"><h2>No applications yet</h2><p>Applications will appear here.</p></div>:items.map(x=><article className="job-card" key={x.id}><div className="proposal-head"><div><span className={"payment-status "+x.status.toLowerCase()}>{x.status}</span><h2>{x.job?.title}</h2></div>{me?.role==="CLIENT"&&x.freelancer&&<OnlineDot isOnline={x.freelancer.isOnline} lastSeen={x.freelancer.lastSeen}/>}</div>{me?.role==="CLIENT"?<><p><b>{x.freelancer?.fullName}</b> · {x.freelancer?.email}</p><p className="online-proposal"><OnlineDot isOnline={x.freelancer?.isOnline} lastSeen={x.freelancer?.lastSeen}/></p><p>{x.coverLetter}</p>{x.status==="PENDING"&&<div className="admin-actions"><button onClick={()=>review(x.id,"ACCEPT")}>Hire freelancer</button><button className="danger-button" onClick={()=>review(x.id,"REJECT")}>Reject</button></div>}</>:<><p>Client: <b>{x.job?.client?.fullName}</b></p><OnlineDot isOnline={x.job?.client?.isOnline} lastSeen={x.job?.client?.lastSeen}/><p>{x.coverLetter}</p>{x.status==="ACCEPTED"&&x.job?.status==="IN_PROGRESS"&&<><div className="escrow-mini-note">Before final release, the client funds the project through <Link href="/escrow">LeonardX Escrow</Link>. You receive 90% after approval.</div><form className="app-form" onSubmit={e=>deliver(x.job.id,e)}><label>Finished work file<input name="file" type="file" required /></label><label>Delivery notes (optional)<textarea name="notes" /></label><button>Submit finished work →</button></form></>}</>}</article>)}</div></AppShell>
}
